-- MySQL Script generated by MySQL Workbench
-- qui 19 nov 2020 15:29:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Atleta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Atleta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Atleta` (
  `ATL_Passaporte` INT NOT NULL,
  `ATL_Nascimento` DATETIME NULL,
  `ATL_Filiacao` VARCHAR(45) NULL,
  `ATL_Sexo` VARCHAR(45) NULL,
  `ATL_Altura` FLOAT NULL,
  `ATL_Peso` INT NULL,
  `ATL_Telefone` VARCHAR(45) CHARACTER SET 'armscii8' NULL,
  `ATL_Licenca` INT NOT NULL,
  `ATL_Treinador` INT NOT NULL,
  `ATL_Delegacao` VARCHAR(45) NOT NULL,
  `ATL_Pais` INT NOT NULL,
  `ATL_Nome` VARCHAR(45) NULL,
  `ATL_Endereco` INT NOT NULL,
  UNIQUE INDEX `ATL_Licenca_UNIQUE` (`ATL_Licenca` ASC) VISIBLE,
  UNIQUE INDEX `ATL_Passaporte_UNIQUE` (`ATL_Passaporte` ASC) VISIBLE,
  PRIMARY KEY (`ATL_Passaporte`),
  INDEX `fk_Atleta_Treinador1_idx` (`ATL_Treinador` ASC) VISIBLE,
  INDEX `fk_Atleta_Delegacao1_idx` (`ATL_Delegacao` ASC) VISIBLE,
  INDEX `fk_Atleta_País1_idx` (`ATL_Pais` ASC) VISIBLE,
  UNIQUE INDEX `ATL_Nascimento_UNIQUE` (`ATL_Nascimento` ASC) VISIBLE,
  UNIQUE INDEX `ATL_Filiacao_UNIQUE` (`ATL_Filiacao` ASC) VISIBLE,
  UNIQUE INDEX `ATL_Sexo_UNIQUE` (`ATL_Sexo` ASC) VISIBLE,
  UNIQUE INDEX `ATL_Altura_UNIQUE` (`ATL_Altura` ASC) VISIBLE,
  UNIQUE INDEX `ATL_Peso_UNIQUE` (`ATL_Peso` ASC) VISIBLE,
  UNIQUE INDEX `ATL_Telefone_UNIQUE` (`ATL_Telefone` ASC) VISIBLE,
  INDEX `fk_Atleta_Endereco1_idx` (`ATL_Endereco` ASC) VISIBLE,
  CONSTRAINT `fk_Atleta_Treinador1`
    FOREIGN KEY (`ATL_Treinador`)
    REFERENCES `mydb`.`Treinador` (`TRE_Passaporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atleta_Delegacao1`
    FOREIGN KEY (`ATL_Delegacao`)
    REFERENCES `mydb`.`Delegacao` (`DEL_Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atleta_País1`
    FOREIGN KEY (`ATL_Pais`)
    REFERENCES `mydb`.`País` (`PAI_Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atleta_Endereco1`
    FOREIGN KEY (`ATL_Endereco`)
    REFERENCES `mydb`.`Endereco` (`END_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Atleta_Equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Atleta_Equipe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Atleta_Equipe` (
  `Atleta_ATL_Licenca` INT NOT NULL,
  `Equipe_EQU_Nome` INT NOT NULL,
  PRIMARY KEY (`Atleta_ATL_Licenca`, `Equipe_EQU_Nome`),
  INDEX `fk_Atleta_has_Equipe_Equipe1_idx` (`Equipe_EQU_Nome` ASC) VISIBLE,
  INDEX `fk_Atleta_has_Equipe_Atleta1_idx` (`Atleta_ATL_Licenca` ASC) VISIBLE,
  CONSTRAINT `fk_Atleta_has_Equipe_Atleta1`
    FOREIGN KEY (`Atleta_ATL_Licenca`)
    REFERENCES `mydb`.`Atleta` (`ATL_Licenca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atleta_has_Equipe_Equipe1`
    FOREIGN KEY (`Equipe_EQU_Nome`)
    REFERENCES `mydb`.`Equipe` (`EQU_Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Atleta_Modalidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Atleta_Modalidade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Atleta_Modalidade` (
  `ATL_MOD_Modalidade` VARCHAR(90) NOT NULL,
  `ATL_MOD_Atleta` INT NOT NULL,
  `ATL_MOD_Posicao` INT NULL,
  PRIMARY KEY (`ATL_MOD_Modalidade`, `ATL_MOD_Atleta`),
  INDEX `fk_Modalidade_Individual_has_Atleta_Atleta1_idx` (`ATL_MOD_Atleta` ASC) VISIBLE,
  INDEX `fk_Modalidade_Individual_has_Atleta_Modalidade_Individual1_idx` (`ATL_MOD_Modalidade` ASC) VISIBLE,
  CONSTRAINT `fk_Modalidade_Individual_has_Atleta_Modalidade_Individual1`
    FOREIGN KEY (`ATL_MOD_Modalidade`)
    REFERENCES `mydb`.`Modalidade_Individual` (`MOD_IND_Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Modalidade_Individual_has_Atleta_Atleta1`
    FOREIGN KEY (`ATL_MOD_Atleta`)
    REFERENCES `mydb`.`Atleta` (`ATL_Licenca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Atletas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Atletas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Atletas` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bairro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bairro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bairro` (
  `BAI_Id` INT NOT NULL,
  `BAI_Nome` VARCHAR(90) NULL,
  PRIMARY KEY (`BAI_Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cidade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `CID_Nome` VARCHAR(90) NOT NULL,
  `CID_UF` INT NOT NULL,
  PRIMARY KEY (`CID_Nome`),
  INDEX `fk_Cidade_UF1_idx` (`CID_UF` ASC) VISIBLE,
  CONSTRAINT `fk_Cidade_UF1`
    FOREIGN KEY (`CID_UF`)
    REFERENCES `mydb`.`UF` (`UF_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Delegacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Delegacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Delegacao` (
  `DEL_Nome` VARCHAR(45) NOT NULL,
  `DEL_Pais` INT NOT NULL,
  PRIMARY KEY (`DEL_Nome`),
  INDEX `fk_Delegacao_País1_idx` (`DEL_Pais` ASC) VISIBLE,
  CONSTRAINT `fk_Delegacao_País1`
    FOREIGN KEY (`DEL_Pais`)
    REFERENCES `mydb`.`País` (`PAI_Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `END_Id` INT NOT NULL,
  `END_CEP` VARCHAR(45) NULL,
  `END_Rua` VARCHAR(45) NULL,
  `END_Comp` VARCHAR(45) NULL,
  `END_Numero` VARCHAR(45) NULL,
  `END_Bairro` INT NOT NULL,
  `END_Cidade` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`END_Id`),
  INDEX `fk_Endereco_Bairro1_idx` (`END_Bairro` ASC) VISIBLE,
  INDEX `fk_Endereco_Cidade1_idx` (`END_Cidade` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Bairro1`
    FOREIGN KEY (`END_Bairro`)
    REFERENCES `mydb`.`Bairro` (`BAI_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_Cidade1`
    FOREIGN KEY (`END_Cidade`)
    REFERENCES `mydb`.`Cidade` (`CID_Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Equipe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Equipe` (
  `EQU_Nome` VARCHAR(45) NOT NULL,
  `EQU_Modalidade` VARCHAR(90) NOT NULL,
  `EQU_Posicao` VARCHAR(45) NULL,
  `EQU_Treinador` INT NOT NULL,
  PRIMARY KEY (`EQU_Nome`),
  INDEX `fk_Equipe_Modalidade_Coletiva_idx` (`EQU_Modalidade` ASC) VISIBLE,
  INDEX `fk_Equipe_Treinador1_idx` (`EQU_Treinador` ASC) VISIBLE,
  CONSTRAINT `fk_Equipe_Modalidade_Coletiva`
    FOREIGN KEY (`EQU_Modalidade`)
    REFERENCES `mydb`.`Modalidade_Coletiva` (`MOD_COL_Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipe_Treinador1`
    FOREIGN KEY (`EQU_Treinador`)
    REFERENCES `mydb`.`Treinador` (`TRE_Passaporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Modalidade_Coletiva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Modalidade_Coletiva` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Modalidade_Coletiva` (
  `MOD_COL_Nome` VARCHAR(90) NOT NULL,
  `MOD_COL_Ano_Inclusao` DATETIME NOT NULL,
  PRIMARY KEY (`MOD_COL_Nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Modalidade_Individual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Modalidade_Individual` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Modalidade_Individual` (
  `MOD_IND_Nome` VARCHAR(90) NOT NULL,
  `MOD_IND_Data_Inclusao` VARCHAR(45) NULL,
  PRIMARY KEY (`MOD_IND_Nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`País`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`País` ;

CREATE TABLE IF NOT EXISTS `mydb`.`País` (
  `PAI_Cod` INT NOT NULL,
  PRIMARY KEY (`PAI_Cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trabalhos_Treinadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Trabalhos_Treinadores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Trabalhos_Treinadores` (
  `TRA_TRE_id` INT NOT NULL,
  `TRA_TRE_Treinador` INT NOT NULL,
  PRIMARY KEY (`TRA_TRE_id`),
  INDEX `fk_Trabalhos_Treinadores_Treinador1_idx` (`TRA_TRE_Treinador` ASC) VISIBLE,
  CONSTRAINT `fk_Trabalhos_Treinadores_Treinador1`
    FOREIGN KEY (`TRA_TRE_Treinador`)
    REFERENCES `mydb`.`Treinador` (`TRE_Passaporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Treinador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Treinador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Treinador` (
  `TRE_Passaporte` INT NOT NULL,
  `TRE_Filiacao` VARCHAR(45) NOT NULL,
  `TRE_Sexo` VARCHAR(45) NOT NULL,
  `TRE_Altura` FLOAT NOT NULL,
  `TRE_Nascimento` DATETIME NOT NULL,
  `TRE_Telefone` VARCHAR(45) NOT NULL,
  `TRE_Peso` INT NOT NULL,
  `TRE_Conf` VARCHAR(45) NOT NULL,
  `TRE_Data_Nomeacao` DATETIME NULL,
  `TRE_Pais` INT NOT NULL,
  `TRE_Delegacao` VARCHAR(45) NOT NULL,
  `TRE_Endereco` INT NOT NULL,
  PRIMARY KEY (`TRE_Passaporte`),
  INDEX `fk_Treinador_País1_idx` (`TRE_Pais` ASC) VISIBLE,
  INDEX `fk_Treinador_Delegacao1_idx` (`TRE_Delegacao` ASC) VISIBLE,
  INDEX `fk_Treinador_Endereco1_idx` (`TRE_Endereco` ASC) VISIBLE,
  CONSTRAINT `fk_Treinador_País1`
    FOREIGN KEY (`TRE_Pais`)
    REFERENCES `mydb`.`País` (`PAI_Cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Treinador_Delegacao1`
    FOREIGN KEY (`TRE_Delegacao`)
    REFERENCES `mydb`.`Delegacao` (`DEL_Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Treinador_Endereco1`
    FOREIGN KEY (`TRE_Endereco`)
    REFERENCES `mydb`.`Endereco` (`END_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UF` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UF` (
  `UF_Id` INT NOT NULL,
  `UF_Sigla` VARCHAR(45) NULL,
  PRIMARY KEY (`UF_Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
